### ISSUE TITLE
Not Banner but Alert

### ISSUE THREAD

**Issue by DenimTornado** [julienXX/terminal-notifier#146]
Hi! That would be cool, if we can show Alerts with confirm but not simple Banner.

Regards!

**Comment by kurisubrooks** [comment]
Unfortunately this isn't a simple change that can be done with code. In order to do this, you need to change the program's notification type in `System Preferences` > `Notifications`, Select your App then change it to the Alert type. Of course this only changes it for your computer, but this is the only way that this can happen, as far as I know.

**Comment by DenimTornado** [comment]
Cool! that what i need. Changed it to Banners through Preferences.
