### ISSUE TITLE
Back to Prior to 1.7 behavior

### ISSUE THREAD

**Issue by rr0ss0rr** [julienXX/terminal-notifier#172]
I was using terminal-notifier and alerter so I appreciate the merge of alerter into terminal-notifier, but now notice all my scripts which were using terminal-notifier will now pause the script waiting for an action on the alert.  As the default behavior of 1.7 breaks all my scripts, is there any way to have terminal-notifier default to the way it use to work (just a banner display) without waiting for an action?

Thanks

**Comment by julienXX** [comment]
I'll try to revert this behavior, in the meantime you can use the `-timeout` option.

**Comment by rr0ss0rr** [comment]
Thanks .. I reverted back to 1.6.3 .. My thought is if you did not use one of the new Alerter options, that terminal-notifier would work as it did in 1.6.3.  Unfortunately, I use terminal-notifier a lot ;-) so it would be a little inconvenient to change it every where.

Thanks again

**Comment by JayBrown** [comment]
Same here… my scripts—and I have a huge amount of them using terminal-notifier.app—don't continue unless I "Close" the t-n alert. Will revert back to v1.6.3, but looking forward to a fix with v1.7.1. But thank you for a great update. :)

**Comment by julienXX** [comment]
@JayBrown @rr0ss0rr you can expect a fix in 1.7.1 quite soon but it seems -activate and -open don't work well in Sierra, I've got to check that before releasing.

**Comment by JayBrown** [comment]
I use the -execute option with the `open` command to open apps, directories, URLs. Always seemed nicer to me. ;)

**Comment by majorsl** [comment]
Just came here to see what was going on with this behavior. Thank you in advance for that coming fix! *phew*

**Comment by navinpeiris** [comment]
hey @julienXX, this is currently blocking ruby guard, elixir ex_unit_notifier etc and those processes don't exit due to the terminal being held up, so thanks so much for the upcoming fix.

In case it helps, this seems to be a problem with this bit here: https://github.com/julienXX/terminal-notifier/commit/67422e7520bc35d36b9e81487e9632bf9aa10d3a#diff-4f90fe8a7b85b78017139b266d8ad8fbR414, where it does not do as advertised, i.e. "Once the notification is delivered we can exit. (Only if no actions or reply)" - it does not simply exit when an action or reply was not specified.

With my Obj-C fu was better, would have loved to send a pull request instead.

**Comment by julienXX** [comment]
1.7.1 is released with the fix to bring back the proper behaviour :)

**Comment by navinpeiris** [comment]
awesome, thanks @julienXX!

**Comment by rr0ss0rr** [comment]
Thanks for the quick fix ..
