### ISSUE TITLE
Always shows small Terminal icon in notification title

### ISSUE THREAD

**Issue by plroebuck** [julienXX/terminal-notifier#248]
# To help us debug your issue please include:
- the macOS version you use: **10.13.4**
- terminal-notifier version: **2.0.0**
- how did you install terminal-notifier?
```bash
$ sudo gem install terminal-notifier
```
- step-by-step reproduction instructions
Example from README _Example Uses_
```bash
$ terminal-notifier -title ProjectX -subtitle "new tag detected" -message "Finished" -appIcon http://vjeantet.fr/images/logo.png
```

## Issue
A small Terminal icon is displayed beside the appIcon, seemingly as part of the title (unlike example README screenshots). What will eliminate it?

**Comment by plroebuck** [comment]
So people have been asking how to solve this same problem from many angles for about [3 years now](#131). Most of the hacks are infeasible for non-bundlers. What's the status of your Radar issue# for this problem?

**Comment by julienXX** [comment]
Hi @plroebuck the screenshots were taken from alerter when we tried to merge the two projects, I should update these.
This issue is very low on my radar as Apple does not provide a way to do it so the only fix is to make a custom build.
I could write a small HowTo in the README if I can figure a simple way.
I don't have the time to provide and maintain custom builds. Sorry I can't fix this for now :/

**Comment by julienXX** [comment]
Have you tried the possible solution with Automator https://github.com/julienXX/terminal-notifier/issues/131#issuecomment-213752559 ?
