### ISSUE TITLE
Can't find instance of NotificationCenter

### ISSUE THREAD

**Issue by tubbo** [julienXX/terminal-notifier#70]
For some reason, `terminal-notifier` doesn't seem to know where my NotificationCenter is?

```
2013-12-21 21:28:53.808 terminal-notifier[83595:1307] [!] Unable to post a notification for the current user (tscott), as it has no running NotificationCenter instance.
```

However, I'm still getting notifications from other apps, so this is very confusing.

Happens every time I run **terminal-notifier** from the command line, or within a Ruby script.

**Comment by laiso** [comment]
In my terminal, this error has resolved when killed tmux sessions.

```
tmux kill-session
tmux
terminal-notifier -message hello
```

**Comment by juanibiapina** [comment]
I had to kill all my tmux sessions.

**Comment by marcelduran** [comment]
Same problem here, but in my case I'm ssh'ing from my **mac** to a **linux** box (both have ssh pub keys, no tmux, no screen, etc):
```bash
[mac] $ ssh linux
```
Then from **linux** ssh session I:
```bash
[linux] $ ssh -t `echo $SSH_CLIENT | awk '{print $1;}'` "terminal-notifier -message 'hello'"
```
And get:
```
2015-07-31 11:24:39.973 terminal-notifier[82492:611643] [!] Unable to post a notification for the current user (marcelduran), as it has no running NotificationCenter instance.
```
From **mac** it works fine:
```
[mac] $ terminal-notifier -message 'hello'"
```
:clap:
Can someone reopen this issue? Thanks.

**Comment by skrobul** [comment]
same here. tmux, terminal-notifier 1.6.3 installed from homebrew

**Comment by arxanas** [comment]
Killing my `tmux` sessions got it working for me as well.

**Comment by markronquillo** [comment]
same here, it isn't working even if tmux is not active.

**Comment by kaylareedhanson** [comment]
Seconding marcelduran's issue. Does not work when sshing from my linux machine. (Not running tmux on my mac at all).

**Comment by ain** [comment]
Has anyone found out why it's not working from within tmux session? Any chance to get rid of the 

     Unable to post a notification for the current user (ain), as it has no running NotificationCenter instance.

**Comment by hanakin** [comment]
same issue i do not know what tmux is and it does not seem to be installed on my mac, im running 1.6.3 installed via npm gulp-notify

**Comment by julienXX** [comment]
@hanakin could you try to remove the version installed by gulp and try again with a fresh one installed via homebrew? Maybe this gulp-notify thing is messing something.

**Comment by hanakin** [comment]
i over wrote it with the download from the release page and it did nothing

**Comment by fisch0920** [comment]
I get this regardless of tmux usage when installing via gem or homebrew.

```bash
feature-fastlane* in ~/dev/eko/ios $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C50
```

**Comment by NateEag** [comment]
I'm experiencing this on Mac OS X 10.14.6 when running `at` jobs, using version 2.0.0:

```bash
$ terminal-notifier --version
terminal-notifier (2.0.0) is a command-line tool to send macOS User Notifications.
...
```

If I run it directly, it works fine:

```bash
$ terminal-notifier -message test
```

but when I run it in an `at` job (which [requires some configuration on OS X](https://unix.stackexchange.com/questions/478823/making-at-work-on-macos/478840#478840)), I get a system email with the above error message:

```bash
$ at '+1 minute'
terminal-notifier -message 'test'
job 25 at Mon May 11 15:36:00 2020
# Wait until atrun processes the job, then...
$ mail
Mail version 8.1 6/6/93.  Type ? for help.
"/var/mail/redacted": 1 message 1 new
>N  1 redacted@REDACTED  Mon May 11 15:36  13/718   "Output from your job "
? 1
...
2020-05-11 15:36:28.970 terminal-notifier[91012:15649122] [!] Unable to post a notification for the current user (redacted), as it has no running NotificationCenter instance.
```

@julienXX Any advice on debugging this, since I can reliably reproduce the issue? I know my way around Xcode from hybrid iOS work, though it's been many years since I did any OS X native development.

**Comment by julienXX** [comment]
@NateEag I think you don’t have access to the GUI when running at

**Comment by NateEag** [comment]
@julienXX Huh, okay. Thanks for responding. I don't understand why that would be but it certainly fits with my experiments so far.

A quick search suggests [this code is relevant](https://github.com/julienXX/terminal-notifier/blame/3ba9ce569e234062d09c8fd01c4be11e56a9fd1b/Terminal%20Notifier/AppDelegate.m#L133), as it's where the error message comes from. 

Viewing [git blame](https://github.com/julienXX/terminal-notifier/blame/3ba9ce569e234062d09c8fd01c4be11e56a9fd1b/Terminal%20Notifier/AppDelegate.m#L132) leads to [this old issue](https://github.com/julienXX/terminal-notifier/issues/29), where some supposed workarounds involving `su` were posted, before the above code was added to the project. Apparently those workarounds did well for their use cases at the time, but they don't for me (I just get an `su: Sorry` message, I think because OS X now deactivates the root user by default).

Even if I use `sudo -u <username> terminal-notifier -message test` in my `at` job, I still get the above error message. Trying to spawn a notification with `osascript` fares no better:

```bash
$ osascript -e 'display notification "What?"'
```

works fine.

```bash
$ at "+1 minute"
osascript -e 'display notification "What?"'
```

yields a similar but more obscure error message suggesting much the same thing:

```
2020-05-11 16:40:11.060 osascript[41721:15843649] Connection to notification center invalid. ServerConnectionFailure: 1 invalidated: 0
```

I don't understand why a process spawned as me cannot see or connect to my running`NotificationCenter` instance, but that certainly seems to be true. 

I know at jobs could kick off while I'm logged out, but this fails even while I'm logged in and can see "Notification Center.app" in Activity Monitor.

In the end, I'm looking for a way to trigger one-off notifications at specific times on OS X from the command-line. Maybe [Hammerspoon's `hs.notify:schedule()`](https://www.hammerspoon.org/docs/hs.notify.html#schedule) would be a fit.
